language: scala
sudo: false
jdk: openjdk11
scala:
- 2.12.10
- 2.13.1

before_install:
- git fetch --tags

stages:
- name: test
- name: release
  if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
  - stage: release
    script: sbt ci-release
