name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        scala: [2_12, 2_13, 3]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
          java-version: 1.8
          distribution: temurin

    - name: Mount caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.cache/coursier
        key: ${{ runner.os }}-sbt-${{matrix.scala}}-${{ hashFiles('**/*.sbt') }}

    - name: Formatting
      run: |
        sbt scalafmtCheck Test/scalafmtCheck scalafmtSbtCheck

    - name: Compile and test (JVM)
      run: |
        sbt coreJVM${{matrix.scala}}/test e2eJVM${{matrix.scala}}/test e2eJVM${{matrix.scala}}/it:test

    - name: Compile and test (JS)
      if: ${{ matrix.scala != 3 }}
      run: |
        sbt coreJS${{matrix.scala}}/test

    - name: Examples
      run: |
        .github/workflows/test_examples.sh

  # Single final job for mergify.
  ci-passed:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: ':'
